/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BaseButton {
    }
    interface SideBarMenu {
        "open": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLBaseButtonElement extends Components.BaseButton, HTMLStencilElement {
    }
    var HTMLBaseButtonElement: {
        prototype: HTMLBaseButtonElement;
        new (): HTMLBaseButtonElement;
    };
    interface HTMLSideBarMenuElement extends Components.SideBarMenu, HTMLStencilElement {
    }
    var HTMLSideBarMenuElement: {
        prototype: HTMLSideBarMenuElement;
        new (): HTMLSideBarMenuElement;
    };
    interface HTMLElementTagNameMap {
        "base-button": HTMLBaseButtonElement;
        "side-bar-menu": HTMLSideBarMenuElement;
    }
}
declare namespace LocalJSX {
    interface BaseButton {
    }
    interface SideBarMenu {
        "open"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "base-button": BaseButton;
        "side-bar-menu": SideBarMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "base-button": LocalJSX.BaseButton & JSXBase.HTMLAttributes<HTMLBaseButtonElement>;
            "side-bar-menu": LocalJSX.SideBarMenu & JSXBase.HTMLAttributes<HTMLSideBarMenuElement>;
        }
    }
}
